version: "3"
services:
  server:
    build: ./server
    ports:
      - "8080:8080"
  client:
    build: ./client
    ports:
      - "80:4173"
  db:
    image: "mysql:8.4"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "test"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql

